# מעלה את התוסף לשרת דרך SFTP
name: Deploy WordPress Plugin via SFTP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload plugin via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 63.250.61.124
          username: myhelper
          password: ${{ secrets.CPANEL_FTP_PASSWORD }}
          port: 2223
          source: "ga4-maccabi-tracking/*"
          target: "/home/junami/public_html/ga4/wp-content/plugins/ga4-maccabi-tracking"
          strip_components: 1